"""first

Revision ID: 09273939a586
Revises: 
Create Date: 2022-07-11 07:16:38.190932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09273939a586'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('population_size', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'reference', name='loc_ref')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locality')
    # ### end Alembic commands ###
